<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="24" time="4.516" timestamp="2025-06-09T13:57:06.960533+01:00" hostname="LPL2-PC-001061"><testcase classname="tests.test_attention_entropy" name="test_attention_entropy_random" file="tests\test_attention_entropy.py" line="8" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_attention_entropy" name="test_attention_entropy_zero" file="tests\test_attention_entropy.py" line="4" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_attention_integration" name="test_attention_integration" file="tests\test_attention_integration.py" line="5" time="0.011"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_attention" name="test_attention_entropy_range" file="tests\test_attention.py" line="4" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_backtest" name="test_robust_backtest_simple" file="tests\test_backtest.py" line="45" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_backtest" name="test_robust_backtest_unbounded_reward" file="tests\test_backtest.py" line="63" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_dataset" name="test_hourlydataset_basic" file="tests\test_dataset.py" line="85" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_dataset" name="test_load_csv_hourly_missing" file="tests\test_dataset.py" line="63" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------
WARNING  root:dataset.py:51 CSV file 'C:\Users\dwrostron\AppData\Local\Temp\pytest-of-dwrostron\pytest-4\test_load_csv_hourly_missing0\nope.csv' not found.
--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_dataset" name="test_load_csv_hourly_parse" file="tests\test_dataset.py" line="68" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_entropy_logits_vs_probs" name="test_entropy_logits_vs_probs" file="tests\test_entropy_logits_vs_probs.py" line="4" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_entropy_range" name="test_entropy_range_logits" file="tests\test_entropy_range.py" line="4" time="0.001"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_entropy_warning" name="test_entropy_warning" file="tests\test_entropy_warning.py" line="10" time="1.063"><system-out>--------------------------------- Captured Log ---------------------------------
WARNING  root:ensemble.py:294 Attention entropy low: 0.40
--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_filters" name="test_reject_if_risky" file="tests\test_filters.py" line="3" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_metrics" name="test_compute_days_in_profit" file="tests\test_metrics.py" line="46" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_metrics" name="test_compute_yearly_stats_basic" file="tests\test_metrics.py" line="60" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_metrics" name="test_inactivity_exponential_penalty" file="tests\test_metrics.py" line="36" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_risk_gate_integration" name="test_gate_triggered" file="tests\test_risk_gate_integration.py" line="3" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rl" name="test_apply_action_custom_space" file="tests\test_rl.py" line="108" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rl" name="test_find_nearest_action" file="tests\test_rl.py" line="69" time="0.007"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rl" name="test_no_warnings" file="tests\test_rl.py" line="147" time="0.002"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_rl" name="test_pick_action_deterministic" file="tests\test_rl.py" line="77" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_scaling" name="test_adaptive_scaler" file="tests\test_scaling.py" line="29" time="0.006"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_selection" name="test_choose_best" file="tests\test_selection.py" line="3" time="0.000"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="tests.test_smoke" name="test_end_to_end_smoke" file="tests\test_smoke.py" line="13" time="1.540"><failure message="assert 0 == 1&#10; +  where 0 = g.epoch_count">def test_end_to_end_smoke():
        sys.modules["openai"] = types.SimpleNamespace()
        data = load_csv_hourly("Gemini_BTCUSD_1h.csv")[:1500]
        assert len(data) &gt; 24
        ensemble = EnsembleModel(
            device=torch.device("cpu"), n_models=1, lr=1e-4, weight_decay=1e-4
        )
        stop_event = threading.Event()
        csv_training_thread(
            ensemble,
            data,
            stop_event,
            {"ADAPT_TO_LIVE": False},
            use_prev_weights=False,
            max_epochs=1,
        )
        result = robust_backtest(ensemble, data)
        assert result["trades"] &gt; 0
&gt;       assert g.epoch_count == 1
E       assert 0 == 1
E        +  where 0 = g.epoch_count

tests\test_smoke.py:32: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------
Traceback (most recent call last):
  File "C:\Users\dwrostron\Documents\GitHub\AI-t-bot\artibot\training.py", line 84, in csv_training_thread
    tl, vl = ensemble.train_one_epoch(dl_train, dl_val, train_data, stop_event)
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dwrostron\Documents\GitHub\AI-t-bot\artibot\ensemble.py", line 163, in train_one_epoch
    for batch_idx, (batch_x, batch_y) in enumerate(dl_train):
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py", line 493, in __iter__
    return self._get_iterator()
           ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py", line 424, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\site-packages\torch\utils\data\dataloader.py", line 1171, in __init__
    w.start()
    ~~~~~~~^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ~~~~~~~~~~~^^^^^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\popen_spawn_win32.py", line 97, in __init__
    reduction.dump(process_obj, to_child)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
_pickle.PicklingError: Can't pickle &lt;class 'artibot.dataset.HourlyDataset'&gt;: it's not the same object as artibot.dataset.HourlyDataset
Traceback (most recent call last):
  File "&lt;string&gt;", line 1, in &lt;module&gt;
    from multiprocessing.spawn import spawn_main; spawn_main(parent_pid=32332, pipe_handle=1140)
                                                  ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\spawn.py", line 113, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
                                     source_process=source_process)
  File "C:\Users\dwrostron\AppData\Local\Programs\Python\Python313\Lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        source_process, handle, target_process,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        0, inheritable, _winapi.DUPLICATE_SAME_ACCESS)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

</system-err></testcase></testsuite></testsuites>